### ISSUE TITLE
Make command confirmations ephemeral

### ISSUE THREAD

**Issue by AriannaStory** [verzac/grocer-discord-bot#22]
When I add things to my grocery list, I'm given [a confirmation message for each individual item](https://user-images.githubusercontent.com/4652603/231926812-1b446337-d329-4b86-9d4d-0a93329ca62e.png) (or each batch with `/grobulk`). Personally, I'm not sure I see the need for the messages to be permanent and live in the channel forever. I'd propose changing these confirmation messages to be [ephemeral](https://support.discord.com/hc/en-us/articles/1500000580222-Ephemeral-Messages-FAQ) (as the API keys output in `/developer`are). 

I personally can't see a need to see a changelog of the grocery list and this would go a long way toward keeping my household's server simple and clean. :)

**Comment by verzac** [comment]
Hey @AriannaStory, sorry for the late reply.

I'm kind of hesitant on introducing this kind of breaking change wholesale, because some people (cough me cough) do find the changelog useful (especially when I'm trying to figure out who put what in, so I can pester them about it).

However, if you're interested, would it be fine if I provide you with a way to configure it for your server? e.g. `/groconfig set ephemeral true` or something like that. Shouldn't be too hard, and frankly I've always wanted a settings page - it's just that no-one has ever explicitly asked for it. 

Fair warning though: this may only be implemented in 2 weeks since I'm busy taking care of my baby while his nannies are on leave.

**Comment by AriannaStory** [comment]
No worries at all! I would be more than happy with a setting. Please take your time; there's no rush. I'm just always glad to see friendly and open-minded open source maintainers. :) Let me know if I can be of any help!

**Comment by verzac** [comment]
Resolved in 40e18825f5a6bc148b0a24df16c42507a6f766a4

Hey @AriannaStory, code for this has been pushed and released on the latest version of the bot. Do try it out and let me know if this works for you.

Side note: if you'd like to support me, do check out my Patreon @ https://www.patreon.com/verzac :)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/15793363/233920640-208024c1-aad3-48f4-8312-787a2bd67191.png">

**Comment by AriannaStory** [comment]
Perfect, @verzac - thanks so much!
